###############################################################################
# Eklipsed Craft
# Minecraft Beta but it runs faster and is made using C (very based)
#
# WARNING: This is free and I don't own Minecraft, this is just for fun okay
#
# This file doesn't get generated by configure, this stays the same
###############################################################################

# Variables
DEPS      := sdl2 sdl2_mixer cglm
DEPS_LINK := sdl2 sdl2_mixer
SRCS      := $(shell find . -name "*.c" | awk '{print substr($$1,3)}')
OBJS      = $(addprefix $(BUILD_DIR)/,$(patsubst %.c,%.o,$(SRCS)))
CC        ?= gcc

# Flags
DEPS_CFLAGS  := $(foreach dep,$(DEPS),$(shell pkg-config --cflags $(dep)))
DEPS_LDFLAGS := $(foreach dep,$(DEPS_LINK),$(shell pkg-config --libs $(dep))) -lvulkan
CFLAGS       := -I$(SRC_DIR) -I$(EXT_DIR)/include $(CFLAGS) $(DEPS_CFLAGS)
LDFLAGS      := $(LDFLAGS) $(DEPS_LDFLAGS)

# Build Modes
ifeq ($(TARGET),dbg)
CFLAGS += -g -O0 -Wall -std=gnu2x
endif
ifeq ($(TARGET),rel)
CFLAGS += -O2 -Wall -std=gnu2x
endif

# Linking
$(PROG): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^
run: $(PROG)
	$(PROG)

# Compiling
# This variable should be used as a macro which takes in
#   $(1) the source file
#   $(2) file.o: prereqs
define COMPILE
$$(BUILD_DIR)/$(dir $(1))$(2)
	mkdir -p $$(dir $$@)
	$(CC) $(CFLAGS) -o $$@ -c $(1)
endef

$(foreach src,$(SRCS),$(eval $(call COMPILE,$(src),$(shell $(CC) $(CFLAGS) -M $(src) | tr -d '\n' | tr '\\' ' '))))

# Clean up
.PHONY: clean
clean:
	rm -rf build_rel/ build_dbg/

